jenkins:
  systemMessage: "Jenkins created for CI/CD project for web application"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: ${ADMIN_PASSWORD:-admin123}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "git-ssh-key"
              username: "admin"
              description: "SSH key for accessing private Git repos"
              privateKeySource:
                directEntry:
                  privateKey: |
                    -----BEGIN OPENSSH PRIVATE KEY-----
                    
                    -----END OPENSSH PRIVATE KEY-----
