jenkins:
  systemMessage: "Jenkins created for CI/CD project for web application"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: ${ADMIN_PASSWORD:-admin123}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
